[R4R] feat(oracle)
ExocoreNetwork/exocore pull request #24
Opened 2024-04-02 19:28 UTC by leonz789

## Description

----

Closes #XXX

2024-04-03 09:53 UTC, MaxMustermann2 commented
Can you please fix the failing workflows?

2024-04-04 11:40 UTC, bwhour approved these changes
reviewed

2024-04-04 11:46 UTC, bwhour commented on x/oracle/keeper/aggregator/aggregator.go
The status field uses an integer type to indicate status (1 for open, 2 for closed). Using enumerated types or constant definitions instead of magic numbers makes the code easier to understand and maintain.

2024-04-04 11:48 UTC, bwhour commented on x/oracle/keeper/aggregator/aggregator_aggregator.go
The **AggregatorContext** contains multiple mappings (e.g. **validatorsPower, rounds, aggregators**) that may be accessed and modified concurrently in a multi-threaded environment. If this is the case, you need to ensure that access to these mappings is thread-safe and may need to use mutex locking or other concurrency control mechanisms

2024-04-04 11:56 UTC, bwhour commented on x/oracle/keeper/aggregator/aggregator_calculator.go
len(r.prices) < cap(r.prices)
Its a good practice taking  takes into account not exceeding the preset capacity.
Is it necessary to take into account other boundary conditions, such as validation of the input parameters ?

2024-04-04 11:58 UTC, bwhour commented on x/oracle/keeper/aggregator/aggregator_calculator.go
Concurrency control needs to be considered when multiple goroutines may access or modify the **deterministicSource** mapping in the calculator.  it is a common requirement to handle concurrency in applications like blockchain and price aggregation.

2024-04-04 12:10 UTC, bwhour commented on x/oracle/keeper/aggregator/aggregator_filter.go
If there exists a pSource with no prices, accessing pSource.Prices[0] will trigger panic

2024-04-04 12:13 UTC, bwhour commented on x/oracle/keeper/aggregator/aggregator_filter.go
Use string concatenation (validator + strconv. Itoa(int(pSource.SourceId))) to generate the mapped key, whether this key generation rule may cause key conflicts

2024-04-04 12:17 UTC, bwhour commented on x/oracle/keeper/aggregator/aggregator_filter.go
For collection operations (Add operations), assuming that they always succeed without checking the return value can hide problems.

2024-04-04 12:22 UTC, bwhour commented on x/oracle/keeper/aggregator/worker.go
Setting f, c, and a to nil in the **seal method** may help with garbage collection, but if there are operations in these objects that require explicit shutdown or cleanup of resources, extra care is needed to ensure that the resources are freed properly

2024-04-04 12:22 UTC, MaxMustermann2 commented on x/oracle/module.go
> +	bankKeeper    types.BankKeeper
Can you add a comment here to say that they are only used in the simulation?

2024-04-04 12:25 UTC, MaxMustermann2 commented on x/oracle/keeper/keeper.go
> +		stakingKeeper stakingkeeper.Keeper
Please convert this to the minimum required interface in `expected_keepers.go`.

2024-04-04 12:25 UTC, bwhour commented on x/oracle/keeper/aggregator/worker.go
_list4Calculator, list4Aggregator := w.f.filtrate(msg)_: if the **filtrate method** encounters any exceptions while processing a message (e.g., the message is formatted incorrectly), the current implementation will not catch or handle those exceptions

2024-04-04 12:29 UTC, MaxMustermann2 requested changes
Not fully reviewed.

2024-04-04 12:29 UTC, MaxMustermann2 commented on x/oracle/keeper/keeper.go
> +		stakingKeeper stakingkeeper.Keeper
Please convert this to the minimum required interface in `expected_keepers.go`.

2024-04-04 12:29 UTC, MaxMustermann2 commented on x/oracle/module.go
> +	bankKeeper    types.BankKeeper
Can you add a comment here to say that they are only used in the simulation?

2024-04-04 12:56 UTC, bwhour commented on x/oracle/keeper/cache/caches.go
im.PSources = append(im.PSources, item.PSources...)
This case is If there are **new PSources** to be added, it will add the entire PSources array to the existing entry, not just the new SourceId. If  if the new PSources array contains some new and some old (already existing in the current entry) SourceIds, then the price sources associated with the old SourceId will be added repeatedly; over time, if new PSources are added frequently, the PSources array in each entry may become very large, affecting data processing and query efficiency。

2024-04-04 12:58 UTC, bwhour commented on x/oracle/keeper/cache/caches.go
functions in this cache file seems no error handling and logging logic.

2024-04-04 13:43 UTC, bwhour commented on x/oracle/keeper/prices.go
> +			k.cdc.Unmarshal(iterator.Value(), &val)
k.cdc.Unmarshal has error return which need to be handle. can k.cdc.MustMarshal ?
<img width="792" alt="image" src="https://github.com/ExocoreNetwork/exocore/assets/8485901/7ee55cc9-f6e2-4d94-a4eb-6f2a83bc324c">

2024-04-04 13:43 UTC, bwhour commented on x/oracle/keeper/prices.go
> +	k.cdc.Unmarshal(b, &price)
k.cdc.Unmarshal has error return which need to be handle. can k.cdc.MustMarshal ?

2024-04-04 13:43 UTC, bwhour commented on x/oracle/keeper/prices.go
> +		k.cdc.Unmarshal(b, &price)
k.cdc.Unmarshal has error return which need to be handle. can k.cdc.MustMarshal ?

2024-04-04 13:53 UTC, bwhour commented on x/oracle/keeper/aggregator/aggregator_calculator.go
> +	if len(r.prices) < cap(r.prices) {
len(r.prices) < cap(r.prices)
Its a good practice taking  takes into account not exceeding the preset capacity.
Is it necessary to take into account other boundary conditions, such as validation of the input parameters ?

2024-04-04 13:54 UTC, bwhour commented on x/oracle/keeper/aggregator/aggregator_calculator.go
> +func (r *roundPrices) updatePriceAndPower(pw *priceAndPower, totalPower *big.Int) (updated bool, confirmed bool) {
In the updatePriceAndPower method, when new prices and weights are added to roundPrices, if any exceptions are encountered (e.g., if pw.price or pw.power is nil), the code doesn't perform error handling

2024-04-08 20:50 UTC, leonz789 commented
Merging with the original branch introduced confusion due to too many commits. I will reconstruct it to create a cleaner version. Apologies for the mess. (will follow this 6-commit structure for easy review)

2024-04-09 15:15 UTC, leonz789 commented
I will close this pr, and #30 will take place for the oracle module feature pr.

2024-04-09 15:15 UTC, closed without merging